In [ ]:
# Nome: Daniel da Costa Lima  RA: 2021.1.08.026

# Departamento de Agricultura dos Estados Unidos
# https://www.kaggle.com/datasets/srishti1209/coffee-imports-in-brazil

Bibliotecas necessárias

In [ ]:
# Análise e manipulação de dados
import pandas as pd

# Manipulação de vetores e matrizes
import numpy as np  

# Geração de gráficos
import plotly
import plotly.offline as py

# Carregar dados CSV
from pandas import read_csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Leitura do banco de dados
filename='/content/drive/MyDrive/Inteligência Artificial/Banco de dados/Coffee_Time Series.csv'
series = pd.read_csv(filename)

# Exibindo os 5 primeiros e 5 últimos elementos da série
series

Month Year  Value of Import
0       Jan-90            26173
1       Feb-90            19159
2       Mar-90            27451
3       Apr-90            26171
4       May-90            28544
..         ...              ...
385     Feb-22           177513
386     Mar-22           185460
387     Apr-22           197431
388     May-22           119075
389     Jun-22           181707

[390 rows x 2 columns]

In [ ]:
# Analisando as informações gerais do Data Frame
series.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Month Year       390 non-null    object
 1   Value of Import  390 non-null    int64 
dtypes: int64(1), object(1)
memory usage: 6.2+ KB


Gráfico da quantidade de importações de café no Brasil de janeiro de 1990 a junho de 2022

In [ ]:
# Gerando o gráfico
import plotly.graph_objs as go 

data = [ go.Scatter(
          x=series['Month Year'],
          y=series['Value of Import'],
          line = dict(color = '#17BECF'),
          opacity = 0.8)]

py.iplot(data)

Associando "Month Year"e "Value of Import"

In [ ]:
# Variável "importacoes" - contém todos os meses/anos e todos os valores de importações de café no Brasil
importacoes = series.loc[:,["Month Year","Value of Import"]] #seleciona as 2 colunas
importacoes

Month Year  Value of Import
0       Jan-90            26173
1       Feb-90            19159
2       Mar-90            27451
3       Apr-90            26171
4       May-90            28544
..         ...              ...
385     Feb-22           177513
386     Mar-22           185460
387     Apr-22           197431
388     May-22           119075
389     Jun-22           181707

[390 rows x 2 columns]

Checando a existência de valores duplicados e/ou nulos

In [ ]:
# Verificação da existência valores duplicados
importacoes.drop_duplicates(inplace=True)

In [ ]:
# Verificação da existência valores nulos
importacoes.dropna(inplace=True)

Criando a matriz de conhecimento


In [ ]:
# Definindo o tamanho da janela deslizante 
janela = 12

# Quantidade de linhas
lin = len(importacoes)    #-janela

# Criando uma matriz de zeros
matriz = np.zeros(((lin - janela), janela+1))
print(matriz)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# Armazenando os valores de importações em um vetor numpy (facilita a indexação)
valores = importacoes["Value of Import"].to_numpy()

# Preenchendo a matriz com os valores do banco de dados
for i in range(lin - janela):
    for j in range(janela + 1):
        matriz[i][j] = valores[i+j]

# Exibindo os elementos da matriz
print(matriz)

[[ 26173.  19159.  27451. ...  25242.  50914.  69158.]
 [ 19159.  27451.  26171. ...  50914.  69158.  61637.]
 [ 27451.  26171.  28544. ...  69158.  61637.  13725.]
 ...
 [ 94671. 118536. 108001. ... 177513. 185460. 197431.]
 [118536. 108001.  81897. ... 185460. 197431. 119075.]
 [108001.  81897.  98620. ... 197431. 119075. 181707.]]


In [ ]:
# Criando o data frame tabela, atribuindo índices às linhas e colunas
tabela = pd.DataFrame(matriz)
tabela.columns = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', 'Saída']
i = 1
tabela.index = range(1, i + len(tabela))
tabela

1         2         3         4         5         6         7  \
1     26173.0   19159.0   27451.0   26171.0   28544.0   17922.0   26481.0   
2     19159.0   27451.0   26171.0   28544.0   17922.0   26481.0   23562.0   
3     27451.0   26171.0   28544.0   17922.0   26481.0   23562.0   31341.0   
4     26171.0   28544.0   17922.0   26481.0   23562.0   31341.0   43549.0   
5     28544.0   17922.0   26481.0   23562.0   31341.0   43549.0   25242.0   
..        ...       ...       ...       ...       ...       ...       ...   
374  112305.0  115099.0   94671.0  118536.0  108001.0   81897.0   98620.0   
375  115099.0   94671.0  118536.0  108001.0   81897.0   98620.0   85452.0   
376   94671.0  118536.0  108001.0   81897.0   98620.0   85452.0  131631.0   
377  118536.0  108001.0   81897.0   98620.0   85452.0  131631.0  120896.0   
378  108001.0   81897.0   98620.0   85452.0  131631.0  120896.0  149556.0   

            8         9        10        11        12     Saída  
1     23562.0   31341.0   43549.0   25242.0   50914.0   69158.0  
2     31341.0   43549.0   25242.0   50914.0   69158.0   61637.0  
3     43549.0   25242.0   50914.0   69158.0   61637.0   13725.0  
4     25242.0   50914.0   69158.0   61637.0   13725.0   34632.0  
5     50914.0   69158.0   61637.0   13725.0   34632.0   24989.0  
..        ...       ...       ...       ...       ...       ...  
374   85452.0  131631.0  120896.0  149556.0  146751.0  177513.0  
375  131631.0  120896.0  149556.0  146751.0  177513.0  185460.0  
376  120896.0  149556.0  146751.0  177513.0  185460.0  197431.0  
377  149556.0  146751.0  177513.0  185460.0  197431.0  119075.0  
378  146751.0  177513.0  185460.0  197431.0  119075.0  181707.0  

[378 rows x 13 columns]